spring:
  application:
    name: "gatewayserver"
  config:
    import: "optional:configserver:http://localhost:8071/"
  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
      access: UNRESTRICTED
  info:
    env:
      enabled: true

info:
  app:
    name: "gatewayserver"
    description: "Axis Bank Gateway Server Application"
    version: "1.0.0"
