spring:
  application:
    name: "eurekaserver"
  config:
    import: "optional:configserver:http://127.0.0.1:8071/"

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true

eureka:
  server:
    renewal-percent-threshold: 0.49
